[package]
name = "d3"
version = "1.0.0"
edition = "2021"
license = "GPL-3.0"
description = "Pure RUST implementation of CRYSTALS-Dilithium3 digital signature scheme"
readme = "README.md"
repository = "https://github.com/valeralabs/d3"
keywords = ["cryptography", "quantum", "dilithium", "digital-signatures", "security"]
categories = ["cryptography", "post-quantum-cryptography"]

[dependencies]
rand = "0.7.3"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "d3_benchmarks"
harness = false